apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: puhzg6km3-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/puhzg6km3-dotnet-basic-gitops